//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendWeb.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class backendMenu
    {
        public string app_id { get; set; }
        public string func_id { get; set; }
        public string controller_id { get; set; }
        public string view_id { get; set; }
        public Nullable<int> func_layer { get; set; }
        public string func_name { get; set; }
        public string func_url { get; set; }
        public Nullable<bool> is_display { get; set; }
        public string sort_order { get; set; }
        public string parent_func_id { get; set; }
        public string icon { get; set; }
        public string authorize_code { get; set; }
    }
}
