//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendWeb.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class backendSetConfig
    {
        public string config_tag { get; set; }
        public string config_tag_name { get; set; }
        public string parent_code { get; set; }
        public string config_code { get; set; }
        public string config_value { get; set; }
        public int status_sort { get; set; }
        public bool is_enable { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
    }
}
