//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendWeb.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class backendUser
    {
        public string account { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string salt_key { get; set; }
        public string register_user { get; set; }
        public Nullable<System.DateTime> register_time { get; set; }
        public Nullable<bool> is_enable { get; set; }
        public Nullable<System.DateTime> disable_time { get; set; }
        public string disable_user { get; set; }
        public string role_group_codes { get; set; }
    }
}
