//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendWeb.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class logJson
    {
        public System.Guid log_id { get; set; }
        public string company { get; set; }
        public string source { get; set; }
        public string request_json { get; set; }
        public Nullable<System.DateTime> request_time { get; set; }
        public string response_json { get; set; }
        public Nullable<System.DateTime> response_time { get; set; }
    }
}
