//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendWeb.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        public System.Guid customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_idcard_no { get; set; }
        public string customer_email { get; set; }
        public Nullable<System.DateTime> customer_birthday { get; set; }
        public string customer_mobile_phone { get; set; }
        public string password { get; set; }
        public string salt_key { get; set; }
        public Nullable<System.DateTime> register_time { get; set; }
        public string sms_verify_code { get; set; }
        public Nullable<bool> sms_is_verify { get; set; }
        public bool is_enable { get; set; }
    }
}
