//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendWeb.Models.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifyCaseStatus
    {
        public int id { get; set; }
        public string dealerNo { get; set; }
        public string branchNo { get; set; }
        public string salesNo { get; set; }
        public string examineNo { get; set; }
        public string examStatusExplain { get; set; }
        public string ModifyTime { get; set; }
        public string QueryCaseStatus { get; set; }
    }
}
